//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFFootball.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPFFootball.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string btnClose {
            get {
                return ResourceManager.GetString("btnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open away team.
        /// </summary>
        public static string gbtnOpenAwayTeam {
            get {
                return ResourceManager.GetString("gbtnOpenAwayTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open home team.
        /// </summary>
        public static string gbtnOpenHomeTeam {
            get {
                return ResourceManager.GetString("gbtnOpenHomeTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string gbtnSettings {
            get {
                return ResourceManager.GetString("gbtnSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Away team.
        /// </summary>
        public static string glblAwayTeam {
            get {
                return ResourceManager.GetString("glblAwayTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home team.
        /// </summary>
        public static string glblHomeTeam {
            get {
                return ResourceManager.GetString("glblHomeTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string glblResult {
            get {
                return ResourceManager.GetString("glblResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game.
        /// </summary>
        public static string gTitle {
            get {
                return ResourceManager.GetString("gTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string mmbtnNo {
            get {
                return ResourceManager.GetString("mmbtnNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string mmbtnYes {
            get {
                return ResourceManager.GetString("mmbtnYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string mmTitle {
            get {
                return ResourceManager.GetString("mmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capetan:.
        /// </summary>
        public static string pdlblCapetan {
            get {
                return ResourceManager.GetString("pdlblCapetan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals scored:.
        /// </summary>
        public static string pdlblGoals {
            get {
                return ResourceManager.GetString("pdlblGoals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow cards:.
        /// </summary>
        public static string pdlblYellowCards {
            get {
                return ResourceManager.GetString("pdlblYellowCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player details.
        /// </summary>
        public static string pdTitle {
            get {
                return ResourceManager.GetString("pdTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string sdbtnNext {
            get {
                return ResourceManager.GetString("sdbtnNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximize.
        /// </summary>
        public static string sdddliMaximize {
            get {
                return ResourceManager.GetString("sdddliMaximize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string sdddliMedium {
            get {
                return ResourceManager.GetString("sdddliMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small.
        /// </summary>
        public static string sdddliSmall {
            get {
                return ResourceManager.GetString("sdddliSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Women.
        /// </summary>
        public static string sdddliWomen {
            get {
                return ResourceManager.GetString("sdddliWomen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Croatian.
        /// </summary>
        public static string sddliCroatian {
            get {
                return ResourceManager.GetString("sddliCroatian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string sddliEnglish {
            get {
                return ResourceManager.GetString("sddliEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Men.
        /// </summary>
        public static string sddliMen {
            get {
                return ResourceManager.GetString("sddliMen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Football championship:.
        /// </summary>
        public static string sdlblChampionship {
            get {
                return ResourceManager.GetString("sdlblChampionship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        public static string sdlblLanguage {
            get {
                return ResourceManager.GetString("sdlblLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window size.
        /// </summary>
        public static string sdlblResolution {
            get {
                return ResourceManager.GetString("sdlblResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings default.
        /// </summary>
        public static string sdTitle {
            get {
                return ResourceManager.GetString("sdTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draws:.
        /// </summary>
        public static string tdlblDraws {
            get {
                return ResourceManager.GetString("tdlblDraws", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games played:.
        /// </summary>
        public static string tdlblGamesPlayed {
            get {
                return ResourceManager.GetString("tdlblGamesPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taken:.
        /// </summary>
        public static string tdlblGaolsTaken {
            get {
                return ResourceManager.GetString("tdlblGaolsTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals differential:.
        /// </summary>
        public static string tdlblGoalsDifferential {
            get {
                return ResourceManager.GetString("tdlblGoalsDifferential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given:.
        /// </summary>
        public static string tdlblGoalsGiven {
            get {
                return ResourceManager.GetString("tdlblGoalsGiven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Losses:.
        /// </summary>
        public static string tdlblLosses {
            get {
                return ResourceManager.GetString("tdlblLosses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wins:.
        /// </summary>
        public static string tdlblWins {
            get {
                return ResourceManager.GetString("tdlblWins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team details.
        /// </summary>
        public static string tdTitle {
            get {
                return ResourceManager.GetString("tdTitle", resourceCulture);
            }
        }
    }
}
